name: Deploy OpenCart 3 via FTP (changed files only)

on:
  push:
    branches:
      - stage

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Prepare changed files list
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt

          echo "Changed files:"
          cat changed_files.txt


      - name: Deploy changed files
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |

          cat > exclude.txt <<'EOF'
          ^\.git
          ^\.github
          ^README\.md
          ^build/
          ^robots\.txt
          ^\.htaccess
          ^\.htpasswd
          ^config\.php
          ^admin/config\.php
          ^admin/cyberstore\.php
          ^cyberstore\.php
          ^php\.ini
          ^image/
          ^storage/cache/
          ^storage/logs/
          ^storage/session/
          ^storage/upload/
          ^storage/download/
          ^storage/modification/
          ^storage/exchange1c/
          ^storage/geoip/
          ^vqmod/logs/
          ^vqmod/vqcache/
          ^install/
          .*\.log$
          .*\.ocmod\.xml$
          EOF


          grep -v -E -f exclude.txt changed_files.txt > deploy_files.txt || true


          echo "Files to deploy:"
          cat deploy_files.txt


          lftp -u "$FTP_USER","$FTP_PASSWORD" "$FTP_HOST" <<EOF

          set ftp:ssl-allow no
          set net:timeout 20
          set net:max-retries 3

          mirror -R \
            --verbose \
            --continue \
            --parallel=10 \
            --files-from deploy_files.txt \
            ./ "$TARGET_DIR"

          quit

EOF